# unused, TODO maybe instead of .py config file in the future
#COMMON: &common
#  DEBUG: False
#  TESTING: False
#  HOST: 0.0.0.0
#  PORT: 5000
#DEVELOPMENT: &development
#  <<: *common
#  DEBUG: True
#PRODUCTION: &production
#  <<: *common
#  HOST: 192.168.1.248