"""init

Revision ID: 2579e237c51a
Revises: 
Create Date: 2019-11-11 15:20:33.685936

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2579e237c51a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_repo',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(length=128), nullable=True),
                    sa.Column('ssh_url_to_repo', sa.String(length=128), nullable=False),
                    sa.Column('http_url_to_repo', sa.String(length=128), nullable=False),
                    sa.Column('web_url', sa.String(length=128), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('name_with_namespace', sa.String(length=64), nullable=False),
                    sa.Column('path', sa.String(length=64), nullable=False),
                    sa.Column('path_with_namespace', sa.String(length=64), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
                    sa.Column('created_by', sa.String(length=32), nullable=False, comment='创建人'),
                    sa.Column('last_updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
                    sa.Column('last_updated_by', sa.String(length=32), nullable=False, comment='最后更新人'),
                    sa.Column('is_deleted', sa.Integer(), nullable=False, comment='是否删除：0表示正常，1表示已删除'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('publishment',
                    sa.Column('id', sa.Integer(), nullable=False, comment='主键id'),
                    sa.Column('name', sa.String(), nullable=False, comment='发布名称'),
                    sa.Column('description', sa.String(), nullable=False, comment='发布描述'),
                    sa.Column('git_repo_id', sa.Integer(), nullable=False, comment='git仓库id'),
                    sa.Column('git_branches', sa.String(length=32), nullable=False, comment='发布的git分支'),
                    sa.Column('profile', sa.String(length=8), nullable=False, comment='发布环境'),
                    sa.Column('to_ip', sa.String(length=64), nullable=False, comment='目标服务器ip，多个以半角逗号分隔'),
                    sa.Column('to_project_home', sa.String(length=64), nullable=False, comment='目标服务器项目主目录'),
                    sa.Column('to_process_name', sa.String(length=32), nullable=False, comment='目标服务器项目进程名'),
                    sa.Column('to_java_opts', sa.String(length=128), nullable=True, comment='JAVA变量'),
                    sa.Column('git_merged_branch', sa.String(length=16), nullable=True, comment='发布完毕后git合并到的分支'),
                    sa.Column('git_tag_version', sa.String(length=16), nullable=True, comment='发布完毕后git打标签名'),
                    sa.Column('git_tag_comment', sa.String(length=128), nullable=True,
                              comment='发布完毕后git打标签备注，依赖于git_tag_version'),
                    sa.Column('git_delete_temp_branch', sa.Integer(), nullable=True,
                              comment='发布完毕后是否删除临时git分支，多分支发布时有效'),
                    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
                    sa.Column('created_by', sa.String(length=32), nullable=False, comment='创建人'),
                    sa.Column('last_updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
                    sa.Column('last_updated_by', sa.String(length=32), nullable=False, comment='最后更新人'),
                    sa.Column('is_deleted', sa.Integer(), nullable=False, comment='是否删除：0表示正常，1表示已删除'),
                    sa.ForeignKeyConstraint(['git_repo_id'], ['git_repo.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('publishment_fe_vue',
                    sa.Column('id', sa.Integer(), nullable=False, comment='主键id'),
                    sa.Column('name', sa.String(), nullable=False, comment='发布名称'),
                    sa.Column('description', sa.String(), nullable=False, comment='发布描述'),
                    sa.Column('git_repo_id', sa.Integer(), nullable=False, comment='git仓库id'),
                    sa.Column('git_branches', sa.String(length=32), nullable=False, comment='发布的git分支'),
                    sa.Column('profile', sa.String(length=8), nullable=False, comment='发布环境'),
                    sa.Column('to_ip', sa.String(length=64), nullable=False, comment='目标服务器ip'),
                    sa.Column('to_project_home', sa.String(length=64), nullable=False, comment='目标服务器主目录'),
                    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
                    sa.Column('created_by', sa.String(length=32), nullable=False, comment='创建人'),
                    sa.Column('last_updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
                    sa.Column('last_updated_by', sa.String(length=32), nullable=False, comment='最后更新人'),
                    sa.Column('is_deleted', sa.Integer(), nullable=False, comment='是否删除：0表示正常，1表示已删除'),
                    sa.ForeignKeyConstraint(['git_repo_id'], ['git_repo.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('publishment_staticfile',
                    sa.Column('id', sa.Integer(), nullable=False, comment='主键id'),
                    sa.Column('name', sa.String(), nullable=False, comment='发布名称'),
                    sa.Column('description', sa.String(), nullable=False, comment='发布描述'),
                    sa.Column('git_repo_id', sa.Integer(), nullable=False, comment='git仓库id'),
                    sa.Column('git_branches', sa.String(length=32), nullable=False, comment='发布的git分支'),
                    sa.Column('to_ip', sa.String(length=64), nullable=False, comment='目标服务器ip'),
                    sa.Column('to_project_home', sa.String(length=64), nullable=False, comment='目标服务器主目录'),
                    sa.ForeignKeyConstraint(['git_repo_id'], ['git_repo.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publishment_staticfile')
    op.drop_table('publishment_fe_vue')
    op.drop_table('publishment')
    op.drop_table('git_repo')
    # ### end Alembic commands ###
